# Generated by Django 6.0.1 on 2026-01-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_designation', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
